import argparse
import json
import sys

parser = argparse.ArgumentParser(
    prog='Predict',
    description='This programm Predict the price of a car given the mileage')

parser.add_argument('--theta0', '-th0', type=float, default=0, help='Value of theta0')
parser.add_argument('--theta1', '-th1', type=float, default=0, help='Value of theta1')
parser.add_argument('--jsonfile', action='store_true', help='Use json file generated by the trainer programm to set theta0 and theta1')
parser.add_argument('--jsonpath', default='results.json', help='Path to json file generated by the trainer programm')

args = parser.parse_args()
print(args)
if args.jsonfile:
    datos = None
    try:
        with open(args.jsonpath, 'r') as jsonfile:
            datos = json.load(jsonfile)
        args.theta0 = datos['theta0']
        args.theta1 = datos['theta1']
    except FileNotFoundError:
        print(f'Error: couldn´t find file {args.jsonpath}')
        sys.exit(1)
    except PermissionError:
        print(f"Permission denied to access {args.jsonpath}")
        sys.exit(1)
    except KeyError:
        print(f"Values of theta0 and/or theta1 no found at {args.jsonpath}")
    except Exception as e:
        print(f"An exception type {type(e).__name__} has ocurred, please check the json file {args.jsonpath}")
        sys.exit(1)

if args.theta0 == 0 or args.theta1 == 0:
    print("The values of theta0 and/or theta1 are 0, likely, those are not the values for a trained model.")
    print("To train your model, please run 'regression.py', if you have done so,")
    print("set up the arguments for theta0 and theta1 manually or use the json file generated by 'regression.py'")
    print("Run 'predict.py --help' for more detailed information")

try:    
    mileage = (float(input("Please, type the mileage: ")))
except ValueError:
        print(f"Mileage must be a float.")
        sys.exit(1)
except Exception as e:
    print(f"An exception type {type(e).__name__} has ocurred, please input a float value as mileage")
    sys.exit(1)
predicted_price = mileage * args.theta1 + args.theta0
print(f"The estimated price is: {predicted_price}")